trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(1)(ff314f7e-40b6-4237-b8c1-b088a098065c)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t mylab231.azurecr.io/web-game:tag 2048-game
            az acr login -n mylab231
            docker push mylab231.azurecr.io/web-game:tag
            
- script: cat 01_kubernetes_aks/app-deploy.yaml
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1(ff314f7e-40b6-4237-b8c1-b088a098065c)'
    azureResourceGroup: 'mylab1-rg'
    kubernetesCluster: 'myk8sservicesnew'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1(1)(ff314f7e-40b6-4237-b8c1-b088a098065c)'
    azureContainerRegistry: 'mylab231.azurecr.io'
    forceUpdate: false